import { jsPDF } from 'jspdf';
import type { ForensicReport } from '../types';

export const exportReportToPDF = (report: ForensicReport) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 15;

  // Header Background Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 40, 'F');

  // Title & Subtitle
  doc.setTextColor(6, 182, 212); // cyan-500
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('PHANTOM PHOENIX', 15, y);

  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text('DIGITAL MEDIA AUTHENTICITY & AI FORENSIC REPORT', 15, y + 6);

  doc.setFontSize(8);
  doc.setTextColor(203, 213, 225);
  doc.text(`REPORT ID: ${report.id}`, pageWidth - 15, y, { align: 'right' });
  doc.text(`DATE: ${new Date(report.createdAt).toLocaleDateString()}`, pageWidth - 15, y + 6, { align: 'right' });

  y = 48;

  // File Details Box
  doc.setFillColor(30, 41, 59); // slate-800
  doc.roundedRect(15, y, pageWidth - 30, 24, 3, 3, 'F');

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(`Analyzed File: ${report.fileName}`, 20, y + 9);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text(`Processing Time: ${report.processingTime}s  |  Analysis Engine Version: ${report.analysisVersion}`, 20, y + 17);

  y += 32;

  // Final Verdict Card
  const isManipulated = report.verdict === 'AI_GENERATED' || report.verdict === 'MANIPULATED';
  const verdictBg = isManipulated ? [127, 29, 29] : [6, 78, 59]; // red-900 / emerald-900
  const verdictText = isManipulated ? [248, 113, 113] : [52, 211, 153];

  doc.setFillColor(verdictBg[0], verdictBg[1], verdictBg[2]);
  doc.roundedRect(15, y, pageWidth - 30, 26, 3, 3, 'F');

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(203, 213, 225);
  doc.text('FORENSIC VERDICT:', 20, y + 10);

  doc.setFontSize(14);
  doc.setTextColor(verdictText[0], verdictText[1], verdictText[2]);
  doc.text(report.verdict.replace('_', ' '), 20, y + 18);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(255, 255, 255);
  doc.text(`Authenticity Score: ${report.authenticityScore}%`, pageWidth - 20, y + 9, { align: 'right' });
  doc.text(`Manipulation Probability: ${report.manipulationProbability}%`, pageWidth - 20, y + 17, { align: 'right' });

  y += 34;

  // Executive Summary
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Executive Summary', 15, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  const summaryText = `Forensic analysis of ${report.fileName} indicates a ${report.manipulationProbability}% probability of AI synthesis. Multi-layer neural network classifiers identified spatial diffusion artifacts consistent with latent generative diffusion models. Dominant Frequency: ${report.frequencyAnalysis.dominantFrequency} with ${report.frequencyAnalysis.anomalyCount} high-frequency anomaly zones.`;
  const splitSummary = doc.splitTextToSize(summaryText, pageWidth - 30);
  doc.text(splitSummary, 15, y);

  y += splitSummary.length * 5 + 8;

  // AI Model Attribution (if available)
  if (report.aiAttribution) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('AI Model Attribution', 15, y);
    y += 6;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    doc.text(`Identified Model: ${report.aiAttribution.model} (${report.aiAttribution.confidence}% confidence)`, 15, y);
    y += 5;
    doc.text(`Technique: ${report.aiAttribution.technique}  |  Class: ${report.aiAttribution.generation}`, 15, y);
    y += 10;
  }

  // Recommendations Section
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Forensic Recommendations', 15, y);
  y += 6;

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);

  report.recommendations.forEach((rec) => {
    doc.text(`• ${rec}`, 15, y);
    y += 5;
  });

  y += 10;

  // Footer
  doc.setDrawColor(226, 232, 240);
  doc.line(15, 280, pageWidth - 15, 280);
  doc.setFontSize(7.5);
  doc.setTextColor(148, 163, 184);
  doc.text('Confidential - Generated by Phantom Phoenix AI Forensic Platform', 15, 285);
  doc.text('Page 1 of 1', pageWidth - 15, 285, { align: 'right' });

  // Save the PDF
  doc.save(`Phantom_Phoenix_Forensic_Report_${report.id}.pdf`);
};
